lib_dir = File.dirname(__FILE__) + '/..'
$LOAD_PATH.unshift lib_dir unless $:.include?(lib_dir)
require 'rubygems'
require 'daily_trivia'
require 'test/unit'
require 'rack/test'
require 'fileutils'
require 'contest'
require 'rr'
ENV['RACK_ENV'] = 'test'